package entity;
// Generated 2018/10/29 7:55:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HopDongLd generated by hbm2java
 */
@Entity
@Table(name = "hop_dong_ld")
public class HopDongLd implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7619661083562782011L;
	private HopDongLdId id;
	private int id_1;
	private String loaihd;
	private Date ngayhieuluc;
	private Date ngayhethieuluc;
	private String congviec;
	private String maql;
	private byte trangthai;

	public HopDongLd() {
	}

	public HopDongLd(HopDongLdId id, int id_1, String loaihd, Date ngayhieuluc, Date ngayhethieuluc, String congviec,
			String maql, byte trangthai) {
		this.id = id;
		this.id_1 = id_1;
		this.loaihd = loaihd;
		this.ngayhieuluc = ngayhieuluc;
		this.ngayhethieuluc = ngayhethieuluc;
		this.congviec = congviec;
		this.maql = maql;
		this.trangthai = trangthai;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "sohd", column = @Column(name = "SOHD", nullable = false, length = 150)),
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 45)) })
	public HopDongLdId getId() {
		return this.id;
	}

	public void setId(HopDongLdId id) {
		this.id = id;
	}

	@Column(name = "ID", nullable = false)
	public int getId_1() {
		return this.id_1;
	}

	public void setId_1(int id_1) {
		this.id_1 = id_1;
	}

	@Column(name = "LOAIHD", nullable = false, length = 45)
	public String getLoaihd() {
		return this.loaihd;
	}

	public void setLoaihd(String loaihd) {
		this.loaihd = loaihd;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NGAYHIEULUC", nullable = false, length = 19)
	public Date getNgayhieuluc() {
		return this.ngayhieuluc;
	}

	public void setNgayhieuluc(Date ngayhieuluc) {
		this.ngayhieuluc = ngayhieuluc;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NGAYHETHIEULUC", nullable = false, length = 19)
	public Date getNgayhethieuluc() {
		return this.ngayhethieuluc;
	}

	public void setNgayhethieuluc(Date ngayhethieuluc) {
		this.ngayhethieuluc = ngayhethieuluc;
	}

	@Column(name = "CONGVIEC", nullable = false, length = 45)
	public String getCongviec() {
		return this.congviec;
	}

	public void setCongviec(String congviec) {
		this.congviec = congviec;
	}

	@Column(name = "MAQL", nullable = false, length = 45)
	public String getMaql() {
		return this.maql;
	}

	public void setMaql(String maql) {
		this.maql = maql;
	}

	@Column(name = "TRANGTHAI", nullable = false)
	public byte getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(byte trangthai) {
		this.trangthai = trangthai;
	}

}
