package entity;
// Generated 2018/10/29 7:55:14 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * HopDongLdId generated by hbm2java
 */
@Embeddable
public class HopDongLdId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3962729276468758687L;
	private String sohd;
	private String username;

	public HopDongLdId() {
	}

	public HopDongLdId(String sohd, String username) {
		this.sohd = sohd;
		this.username = username;
	}

	@Column(name = "SOHD", nullable = false, length = 150)
	public String getSohd() {
		return this.sohd;
	}

	public void setSohd(String sohd) {
		this.sohd = sohd;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof HopDongLdId))
			return false;
		HopDongLdId castOther = (HopDongLdId) other;

		return ((this.getSohd() == castOther.getSohd()) || (this.getSohd() != null && castOther.getSohd() != null
				&& this.getSohd().equals(castOther.getSohd())))
				&& ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
						&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getSohd() == null ? 0 : this.getSohd().hashCode());
		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		return result;
	}

}
