package entity;
// Generated 2018/10/29 7:55:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Luong generated by hbm2java
 */
@Entity
@Table(name = "luong")
public class Luong implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3511440915310173100L;
	private String maql;
	private int id;
	private Date tungay;
	private Date denngay;
	private byte trangthai;

	public Luong() {
	}

	public Luong(String maql, int id, Date tungay, Date denngay, byte trangthai) {
		this.maql = maql;
		this.id = id;
		this.tungay = tungay;
		this.denngay = denngay;
		this.trangthai = trangthai;
	}

	@Id

	@Column(name = "MAQL", unique = true, nullable = false, length = 45)
	public String getMaql() {
		return this.maql;
	}

	public void setMaql(String maql) {
		this.maql = maql;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "TUNGAY", nullable = false, length = 19)
	public Date getTungay() {
		return this.tungay;
	}

	public void setTungay(Date tungay) {
		this.tungay = tungay;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "DENNGAY", nullable = false, length = 19)
	public Date getDenngay() {
		return this.denngay;
	}

	public void setDenngay(Date denngay) {
		this.denngay = denngay;
	}

	@Column(name = "TRANGTHAI", nullable = false)
	public byte getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(byte trangthai) {
		this.trangthai = trangthai;
	}

}
