package entity;
// Generated 2018/10/29 7:55:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * NhanVien generated by hbm2java
 */
@Entity
@Table(name = "nhan_vien")
public class NhanVien implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1590073987308083430L;
	private String manv;
	private int id;
	private String hoten;
	private int gioitinh;
	private Date ns;
	private String email;
	private byte trangthai;

	public NhanVien() {
	}

	public NhanVien(String manv, int id, String hoten, int gioitinh, Date ns, String email, byte trangthai) {
		this.manv = manv;
		this.id = id;
		this.hoten = hoten;
		this.gioitinh = gioitinh;
		this.ns = ns;
		this.email = email;
		this.trangthai = trangthai;
	}

	@Id

	@Column(name = "MANV", unique = true, nullable = false, length = 45)
	public String getManv() {
		return this.manv;
	}

	public void setManv(String manv) {
		this.manv = manv;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "HOTEN", nullable = false, length = 50)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "GIOITINH", nullable = false)
	public int getGioitinh() {
		return this.gioitinh;
	}

	public void setGioitinh(int gioitinh) {
		this.gioitinh = gioitinh;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "NS", nullable = false, length = 19)
	public Date getNs() {
		return this.ns;
	}

	public void setNs(Date ns) {
		this.ns = ns;
	}

	@Column(name = "EMAIL", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "TRANGTHAI", nullable = false)
	public byte getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(byte trangthai) {
		this.trangthai = trangthai;
	}

}
