package entity;
// Generated Sep 30, 2018 11:52:56 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * NhanVienId generated by hbm2java
 */

@Embeddable
public class NhanVienId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5206699052153595875L;
	private String manv;
	private int id;

	public NhanVienId() {
	}

	public NhanVienId(String manv, int id) {
		this.manv = manv;
		this.id = id;
	}

	@Column(name = "MANV", nullable = false, length = 45)
	public String getManv() {
		return this.manv;
	}

	public void setManv(String manv) {
		this.manv = manv;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof NhanVienId))
			return false;
		NhanVienId castOther = (NhanVienId) other;

		return ((this.getManv() == castOther.getManv()) || (this.getManv() != null && castOther.getManv() != null
				&& this.getManv().equals(castOther.getManv()))) && (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getManv() == null ? 0 : this.getManv().hashCode());
		result = 37 * result + this.getId();
		return result;
	}

}
