package entity;
// Generated 2018/10/29 7:55:14 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * SoYeuLiLich generated by hbm2java
 */
@Entity
@Table(name = "so_yeu_li_lich")
public class SoYeuLiLich implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5906068284700673389L;
	private String maql;
	private int id;
	private String sdt;
	private String noisinh;
	private String quequan;
	private String dantoc;
	private String tongiao;
	private String noidkhktt;
	private String noiohn;
	private String anh;
	private byte trangthai;

	public SoYeuLiLich() {
	}

	public SoYeuLiLich(String maql, int id, String sdt, String noisinh, String quequan, String dantoc, String tongiao,
			String noidkhktt, String noiohn, byte trangthai) {
		this.maql = maql;
		this.id = id;
		this.sdt = sdt;
		this.noisinh = noisinh;
		this.quequan = quequan;
		this.dantoc = dantoc;
		this.tongiao = tongiao;
		this.noidkhktt = noidkhktt;
		this.noiohn = noiohn;
		this.trangthai = trangthai;
	}

	public SoYeuLiLich(String maql, int id, String sdt, String noisinh, String quequan, String dantoc, String tongiao,
			String noidkhktt, String noiohn, String anh, byte trangthai) {
		this.maql = maql;
		this.id = id;
		this.sdt = sdt;
		this.noisinh = noisinh;
		this.quequan = quequan;
		this.dantoc = dantoc;
		this.tongiao = tongiao;
		this.noidkhktt = noidkhktt;
		this.noiohn = noiohn;
		this.anh = anh;
		this.trangthai = trangthai;
	}

	@Id

	@Column(name = "MAQL", unique = true, nullable = false, length = 45)
	public String getMaql() {
		return this.maql;
	}

	public void setMaql(String maql) {
		this.maql = maql;
	}

	@Column(name = "id", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "SDT", nullable = false, length = 45)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "NOISINH", nullable = false, length = 150)
	public String getNoisinh() {
		return this.noisinh;
	}

	public void setNoisinh(String noisinh) {
		this.noisinh = noisinh;
	}

	@Column(name = "QUEQUAN", nullable = false, length = 150)
	public String getQuequan() {
		return this.quequan;
	}

	public void setQuequan(String quequan) {
		this.quequan = quequan;
	}

	@Column(name = "DANTOC", nullable = false, length = 45)
	public String getDantoc() {
		return this.dantoc;
	}

	public void setDantoc(String dantoc) {
		this.dantoc = dantoc;
	}

	@Column(name = "TONGIAO", nullable = false, length = 45)
	public String getTongiao() {
		return this.tongiao;
	}

	public void setTongiao(String tongiao) {
		this.tongiao = tongiao;
	}

	@Column(name = "NOIDKHKTT", nullable = false, length = 100)
	public String getNoidkhktt() {
		return this.noidkhktt;
	}

	public void setNoidkhktt(String noidkhktt) {
		this.noidkhktt = noidkhktt;
	}

	@Column(name = "NOIOHN", nullable = false, length = 45)
	public String getNoiohn() {
		return this.noiohn;
	}

	public void setNoiohn(String noiohn) {
		this.noiohn = noiohn;
	}

	@Column(name = "ANH", length = 45)
	public String getAnh() {
		return this.anh;
	}

	public void setAnh(String anh) {
		this.anh = anh;
	}

	@Column(name = "TRANGTHAI", nullable = false)
	public byte getTrangthai() {
		return this.trangthai;
	}

	public void setTrangthai(byte trangthai) {
		this.trangthai = trangthai;
	}

}
