package entity;
// Generated 2018/10/29 7:55:14 by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TimeSheetId generated by hbm2java
 */
@Embeddable
public class TimeSheetId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1890490740073842475L;
	private String username;
	private int id;

	public TimeSheetId() {
	}

	public TimeSheetId(String username, int id) {
		this.username = username;
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "ID", nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof TimeSheetId))
			return false;
		TimeSheetId castOther = (TimeSheetId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& (this.getId() == castOther.getId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + this.getId();
		return result;
	}

}
