package entity;
// Generated 2018/10/29 7:55:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.springframework.format.annotation.DateTimeFormat;

/**
 * TimeSheet generated by hbm2java
 */
@Entity
@Table(name = "time_sheet")
public class TimeSheet implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8972464803554724539L;
	private TimeSheetId id;
	
	@DateTimeFormat(pattern="yyyy-MM-dd")
	private Date ngayThang;
	
	private String idLeader;
	
	@DateTimeFormat(pattern="mm/dd/yyyy hh:mm:ss")
	private Date gioBatDauHc;
	private String congViec;
	
	@DateTimeFormat(pattern="mm/dd/yyyy hh:mm:ss")
	private Date gioBatDauOt;
	
	@DateTimeFormat(pattern="mm/dd/yyyy hh:mm:ss")
	private Date gioKetThucOt;
	
	private Byte trangThai;
	
	@DateTimeFormat(pattern="mm/dd/yyyy hh:mm:ss")
	private Date gioNghiOt;
	
	@DateTimeFormat(pattern="mm/dd/yyyy hh:mm:ss")
	private Date gioKetThucHc;
	
	private Integer nghiTruaHc;
	private Integer tongGioHc;
	private Integer tongGioOt;

	public TimeSheet() {
	}

	public TimeSheet(TimeSheetId id, Date ngayThang, Date gioBatDauHc, String congViec, Date gioBatDauOt,
			Date gioKetThucOt, Date gioNghiOt, Date gioKetThucHc) {
		this.id = id;
		this.ngayThang = ngayThang;
		this.gioBatDauHc = gioBatDauHc;
		this.congViec = congViec;
		this.gioBatDauOt = gioBatDauOt;
		this.gioKetThucOt = gioKetThucOt;
		this.gioNghiOt = gioNghiOt;
		this.gioKetThucHc = gioKetThucHc;
	}

	public TimeSheet(TimeSheetId id, Date ngayThang, String idLeader, Date gioBatDauHc, String congViec,
			Date gioBatDauOt, Date gioKetThucOt, Byte trangThai, Date gioNghiOt, Date gioKetThucHc, Integer nghiTruaHc,
			Integer tongGioHc, Integer tongGioOt) {
		this.id = id;
		this.ngayThang = ngayThang;
		this.idLeader = idLeader;
		this.gioBatDauHc = gioBatDauHc;
		this.congViec = congViec;
		this.gioBatDauOt = gioBatDauOt;
		this.gioKetThucOt = gioKetThucOt;
		this.trangThai = trangThai;
		this.gioNghiOt = gioNghiOt;
		this.gioKetThucHc = gioKetThucHc;
		this.nghiTruaHc = nghiTruaHc;
		this.tongGioHc = tongGioHc;
		this.tongGioOt = tongGioOt;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "username", column = @Column(name = "username", nullable = false, length = 45)),
			@AttributeOverride(name = "id", column = @Column(name = "ID", nullable = false)) })
	public TimeSheetId getId() {
		return this.id;
	}

	public void setId(TimeSheetId id) {
		this.id = id;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngayThang", nullable = false, length = 19)
	public Date getNgayThang() {
		return this.ngayThang;
	}

	public void setNgayThang(Date ngayThang) {
		this.ngayThang = ngayThang;
	}

	@Column(name = "idLeader", length = 45)
	public String getIdLeader() {
		return this.idLeader;
	}

	public void setIdLeader(String idLeader) {
		this.idLeader = idLeader;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "gioBatDauHC", nullable = false, length = 8)
	public Date getGioBatDauHc() {
		return this.gioBatDauHc;
	}

	public void setGioBatDauHc(Date gioBatDauHc) {
		this.gioBatDauHc = gioBatDauHc;
	}

	@Column(name = "congViec", nullable = false, length = 16777215)
	public String getCongViec() {
		return this.congViec;
	}

	public void setCongViec(String congViec) {
		this.congViec = congViec;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "gioBatDauOt", nullable = false, length = 8)
	public Date getGioBatDauOt() {
		return this.gioBatDauOt;
	}

	public void setGioBatDauOt(Date gioBatDauOt) {
		this.gioBatDauOt = gioBatDauOt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "gioKetThucOt", nullable = false, length = 8)
	public Date getGioKetThucOt() {
		return this.gioKetThucOt;
	}

	public void setGioKetThucOt(Date gioKetThucOt) {
		this.gioKetThucOt = gioKetThucOt;
	}

	@Column(name = "trangThai")
	public Byte getTrangThai() {
		return this.trangThai;
	}

	public void setTrangThai(Byte trangThai) {
		this.trangThai = trangThai;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "gioNghiOt", nullable = false, length = 8)
	public Date getGioNghiOt() {
		return this.gioNghiOt;
	}

	public void setGioNghiOt(Date gioNghiOt) {
		this.gioNghiOt = gioNghiOt;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "gioKetThucHc", nullable = false, length = 8)
	public Date getGioKetThucHc() {
		return this.gioKetThucHc;
	}

	public void setGioKetThucHc(Date gioKetThucHc) {
		this.gioKetThucHc = gioKetThucHc;
	}

	@Column(name = "nghiTruaHc")
	public Integer getNghiTruaHc() {
		return this.nghiTruaHc;
	}

	public void setNghiTruaHc(Integer nghiTruaHc) {
		this.nghiTruaHc = nghiTruaHc;
	}

	@Column(name = "tongGioHc")
	public Integer getTongGioHc() {
		return this.tongGioHc;
	}

	public void setTongGioHc(Integer tongGioHc) {
		this.tongGioHc = tongGioHc;
	}

	@Column(name = "tongGioOT")
	public Integer getTongGioOt() {
		return this.tongGioOt;
	}

	public void setTongGioOt(Integer tongGioOt) {
		this.tongGioOt = tongGioOt;
	}

}
