package entity;
// Generated 2018/10/29 7:55:14 by Hibernate Tools 3.5.0.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user")
public class User implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4573710704882650803L;
	private long id;
	private String username;
	private String password;
	private String firstName;
	private String lastName;
	private String authority;
	private String deleteFlg;
	private String address;
	private String avatar;
	private String hoten;
	private String sdt;
	private String email;
	private String quequan;
	private String socmt;
	private Date ngaycap;
	private String noicap;

	public User() {
	}

	public User(long id, String username, String password, String firstName, String lastName, String authority,
			String deleteFlg, String address, String avatar, String hoten, String sdt, String email, String quequan,
			String socmt, Date ngaycap, String noicap) {
		this.id = id;
		this.username = username;
		this.password = password;
		this.firstName = firstName;
		this.lastName = lastName;
		this.authority = authority;
		this.deleteFlg = deleteFlg;
		this.address = address;
		this.avatar = avatar;
		this.hoten = hoten;
		this.sdt = sdt;
		this.email = email;
		this.quequan = quequan;
		this.socmt = socmt;
		this.ngaycap = ngaycap;
		this.noicap = noicap;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	public void setId(long id) {
		this.id = id;
	}

	@Column(name = "username", nullable = false, length = 50)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 500)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "first_name", nullable = false, length = 50)
	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	@Column(name = "last_name", nullable = false, length = 50)
	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	@Column(name = "authority", nullable = false, length = 1)
	public String getAuthority() {
		return this.authority;
	}

	public void setAuthority(String authority) {
		this.authority = authority;
	}

	@Column(name = "delete_flg", nullable = false, length = 1)
	public String getDeleteFlg() {
		return this.deleteFlg;
	}

	public void setDeleteFlg(String deleteFlg) {
		this.deleteFlg = deleteFlg;
	}

	@Column(name = "address", nullable = false, length = 500)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "avatar", nullable = false, length = 500)
	public String getAvatar() {
		return this.avatar;
	}

	public void setAvatar(String avatar) {
		this.avatar = avatar;
	}

	@Column(name = "hoten", nullable = false, length = 45)
	public String getHoten() {
		return this.hoten;
	}

	public void setHoten(String hoten) {
		this.hoten = hoten;
	}

	@Column(name = "sdt", nullable = false, length = 45)
	public String getSdt() {
		return this.sdt;
	}

	public void setSdt(String sdt) {
		this.sdt = sdt;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "quequan", nullable = false, length = 100)
	public String getQuequan() {
		return this.quequan;
	}

	public void setQuequan(String quequan) {
		this.quequan = quequan;
	}

	@Column(name = "socmt", nullable = false, length = 45)
	public String getSocmt() {
		return this.socmt;
	}

	public void setSocmt(String socmt) {
		this.socmt = socmt;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ngaycap", nullable = false, length = 19)
	public Date getNgaycap() {
		return this.ngaycap;
	}

	public void setNgaycap(Date ngaycap) {
		this.ngaycap = ngaycap;
	}

	@Column(name = "noicap", nullable = false, length = 45)
	public String getNoicap() {
		return this.noicap;
	}

	public void setNoicap(String noicap) {
		this.noicap = noicap;
	}

}
